### ISSUE TITLE
Error: No callback provied - when running with semantic-release@11.1.0

### ISSUE THREAD

**Issue by arlac77** [semantic-release/cracks#11]
```txt
[Semantic release]: An error occurred while running semantic-release: Error: No callback provied.
    at exports.default (/home/travis/build/arlac77/config-expander/node_modules/cracks/dist/index.js:23:11)
    at Object.verifyRelease (/home/travis/build/arlac77/config-expander/node_modules/semantic-release/lib/plugins/normalize.js:41:26)
    at module.exports (/home/travis/build/arlac77/config-expander/node_modules/semantic-release/index.js:41:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

**Comment by pvdlg** [comment]
That's because the plugin was not adapted for recent version of semantic-release.
Since [v11.0.0](https://github.com/semantic-release/semantic-release/releases/tag/v11.0.0) plugins must export and async function instead of a regular one with a callback.

PR welcome to adapt this plugin.

**Comment by arlac77** [comment]
ok will try my best.
can i drop pre v11.0.0 compatibility and go to a all new version using async/await (maybe using execa)?

**Comment by pvdlg** [comment]
As far as I'm concerned, yes. Unless someone else has an objection.

**Comment by pvdlg** [comment]
Close in favor of #12
